# Generated by Django 4.0.1 on 2022-02-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(),
        ),
    ]
